#! /bin/bash

clear

rm -rf dist

if [[ $1 == '--dev' ]]; then

  echo """
  ====================
  DEVELOPING JS BUNDLE
  ====================
  """

  TS_NODE_PROJECT=tsconfig.webpack.json \
    DEBUG=true \
    DEV_PORT=3000 \
    NODE_ENV=development \
    ./node_modules/.bin/webpack-dev-server \
    --colors \
    --hot \
    --inline \
    --config webpack.config.ts \
    --mode development

else

  echo """
  ==================
  BUILDING JS BUNDLE
  ==================

  (Use --dev for watch mode)

  """

  TS_NODE_PROJECT=tsconfig.webpack.json \
    NODE_ENV=production \
    BASE_HREF=$1 \
    ./node_modules/.bin/webpack \
    --colors \
    --config webpack.config.ts \
    --mode production \
    --verbose \
    --json >compilation-stats.json

  cp -r $PWD/images $PWD/dist/images

fi
