#! /bin/bash

clear

rm -rf dist
./_build_js_bundle pds-node-nav

node -e '''
  const ghpages = require("gh-pages");

  const GITHUB_USER_NAME = "dan-drago";
  const GITHUB_REPO_NAME = "pds-node-nav";

  console.log("DEPLOYING...");

  ghpages.publish("dist", function (err) {
    if (!!err) {
      console.log(`OH NO! STH WENT WRONG :(`, err);
      process.exit(1);
    }
    console.log(`DEPLOYED TO: https://${GITHUB_USER_NAME}.github.io/${GITHUB_REPO_NAME}/`);
  })
'''
